"""Python stubs for the native-tls Rust crate.

Install with: cookcrab install native-tls
"""

from __future__ import annotations

from typing import Self

class Error:
    """An error returned from the TLS implementation."""

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: ErrorStack) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

class Identity:
    """A cryptographic identity.

An identity is an X509 certificate along with its corresponding private key and chain of certificates to a trusted
root."""

    @staticmethod
    def from_pkcs12(der: object, password: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(_: object, _1: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(buf: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

class Certificate:
    """An X509 certificate."""

    @staticmethod
    def from_der(der: object) -> "Certificate": ...

    @staticmethod
    def from_pem(pem: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(_: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

class MidHandshakeTlsStream:
    """A TLS stream which has been interrupted midway through the handshake process."""

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

class TlsConnectorBuilder:
    """A builder for `TlsConnector`s.

You can get one from [`TlsConnector::builder()`](TlsConnector::builder)"""

    def identity(self, identity: Identity) -> TlsConnectorBuilder: ...

    def min_protocol_version(self, protocol: Protocol | None) -> TlsConnectorBuilder: ...

    def max_protocol_version(self, protocol: Protocol | None) -> TlsConnectorBuilder: ...

    def add_root_certificate(self, cert: Certificate) -> TlsConnectorBuilder: ...

    def disable_built_in_roots(self, disable: bool) -> TlsConnectorBuilder: ...

    def request_alpns(self, protocols: object) -> TlsConnectorBuilder: ...

    def danger_accept_invalid_certs(self, accept_invalid_certs: bool) -> TlsConnectorBuilder: ...

    def use_sni(self, use_sni: bool) -> TlsConnectorBuilder: ...

    def danger_accept_invalid_hostnames(self, accept_invalid_hostnames: bool) -> TlsConnectorBuilder: ...

    def build(self) -> TlsConnector: ...

class TlsConnector:
    """A builder for client-side TLS connections.

# Examples

```rust
use native_tls::TlsConnector;
use std::io::{Read, Write};
use std::net::TcpStream;

let connector = TlsConnector::new().unwrap();

let stream = TcpStream::connect("google.com:443").unwrap();
let mut stream = connector.connect("google.com", stream).unwrap();

stream.write_all(b"GET / HTTP/1.0\\r\\n\\r\\n").unwrap();
let mut res = vec![];
stream.read_to_end(&mut res).unwrap();
println!("{}", String::from_utf8_lossy(&res));
```"""

    @staticmethod
    def new() -> "TlsConnector": ...

    @staticmethod
    def builder() -> TlsConnectorBuilder: ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

class TlsAcceptorBuilder:
    """A builder for `TlsAcceptor`s.

You can get one from [`TlsAcceptor::builder()`](TlsAcceptor::builder)"""

    def min_protocol_version(self, protocol: Protocol | None) -> TlsAcceptorBuilder: ...

    def max_protocol_version(self, protocol: Protocol | None) -> TlsAcceptorBuilder: ...

    def build(self) -> TlsAcceptor: ...

class TlsAcceptor:
    """A builder for server-side TLS connections.

# Examples

```rust,no_run
use native_tls::{Identity, TlsAcceptor, TlsStream};
use std::fs::File;
use std::io::{Read};
use std::net::{TcpListener, TcpStream};
use std::sync::Arc;
use std::thread;

let mut file = File::open("identity.pfx").unwrap();
let mut identity = vec![];
file.read_to_end(&mut identity).unwrap();
let identity = Identity::from_pkcs12(&identity, "hunter2").unwrap();

let listener = TcpListener::bind("0.0.0.0:8443").unwrap();
let acceptor = TlsAcceptor::new(identity).unwrap();
let acceptor = Arc::new(acceptor);

fn handle_client(stream: TlsStream<TcpStream>) {
// ...
}

for stream in listener.incoming() {
match stream {
Ok(stream) => {
let acceptor = acceptor.clone();
thread::spawn(move || {
let stream = acceptor.accept(stream).unwrap();
handle_client(stream);
});
}
Err(e) => { /* connection failed */ }
}
}
```"""

    @staticmethod
    def new(identity: Identity) -> "TlsAcceptor": ...

    @staticmethod
    def builder(identity: Identity) -> TlsAcceptorBuilder: ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

class TlsStream:
    """A stream managing a TLS session."""

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

class Error:

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: ErrorStack) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

class Identity:

    @staticmethod
    def from_pkcs12(der: object, password: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(_: object, _1: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(buf: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

class Certificate:

    @staticmethod
    def from_der(der: object) -> "Certificate": ...

    @staticmethod
    def from_pem(pem: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(_: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

class TlsConnector:

    @staticmethod
    def new() -> "TlsConnector": ...

    @staticmethod
    def builder() -> TlsConnectorBuilder: ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

class TlsAcceptor:

    @staticmethod
    def new(identity: Identity) -> "TlsAcceptor": ...

    @staticmethod
    def builder(identity: Identity) -> TlsAcceptorBuilder: ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

class TlsStream:

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

class Identity:

    @staticmethod
    def from_pkcs12(der: object, password: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(_: object, _1: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(buf: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

class Certificate:

    @staticmethod
    def from_der(der: object) -> "Certificate": ...

    @staticmethod
    def from_pem(pem: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(_: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

class MidHandshakeTlsStream:

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

class TlsConnector:

    @staticmethod
    def new() -> "TlsConnector": ...

    @staticmethod
    def builder() -> TlsConnectorBuilder: ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

class TlsAcceptor:

    @staticmethod
    def new(identity: Identity) -> "TlsAcceptor": ...

    @staticmethod
    def builder(identity: Identity) -> TlsAcceptorBuilder: ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

class TlsStream:

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

class Error:

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: ErrorStack) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

class Identity:

    @staticmethod
    def from_pkcs12(der: object, password: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(_: object, _1: object) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(buf: object, key: object) -> "Identity": ...

    @staticmethod
    def from_pkcs12(buf: object, pass_: str) -> "Identity": ...

    @staticmethod
    def from_pkcs8(pem: object, key: object) -> "Identity": ...

class Certificate:

    @staticmethod
    def from_der(der: object) -> "Certificate": ...

    @staticmethod
    def from_pem(pem: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(_: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

    @staticmethod
    def from_der(buf: object) -> "Certificate": ...

    @staticmethod
    def from_pem(buf: object) -> "Certificate": ...

    def to_der(self) -> list[int]: ...

class MidHandshakeTlsStream:

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

class TlsConnector:

    @staticmethod
    def new() -> "TlsConnector": ...

    @staticmethod
    def builder() -> TlsConnectorBuilder: ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def new(builder: TlsConnectorBuilder) -> "TlsConnector": ...

    def connect(self, domain: str, stream: S) -> object: ...

class TlsAcceptor:

    @staticmethod
    def new(identity: Identity) -> "TlsAcceptor": ...

    @staticmethod
    def builder(identity: Identity) -> TlsAcceptorBuilder: ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

    @staticmethod
    def new(builder: TlsAcceptorBuilder) -> "TlsAcceptor": ...

    def accept(self, stream: S) -> object: ...

class TlsStream:

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def buffered_read_size(self) -> int: ...

    def peer_certificate(self) -> Certificate | None: ...

    def negotiated_alpn(self) -> list[int] | None: ...

    def tls_server_end_point(self) -> list[int] | None: ...

    def shutdown(self) -> object: ...

    def read(self, buf: object) -> int: ...

    def write(self, buf: object) -> int: ...

    def flush(self) -> object: ...

class PemBlock:
    """Split data by PEM guard lines"""

    @staticmethod
    def new(data: object) -> "PemBlock": ...

    def next(self) -> Item | None: ...

class HandshakeError:
    """An error returned from `ClientBuilder::handshake`."""
    Failure: "HandshakeError"
    WouldBlock: "HandshakeError"

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: ErrorStack) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

class Protocol:
    """SSL/TLS protocol versions."""
    Sslv3: "Protocol"
    Tlsv10: "Protocol"
    Tlsv11: "Protocol"
    Tlsv12: "Protocol"

class HandshakeError:
    WouldBlock: "HandshakeError"
    Failure: "HandshakeError"

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: ErrorStack) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

class MidHandshakeTlsStream:
    Server: "MidHandshakeTlsStream"
    Client: "MidHandshakeTlsStream"

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def get_ref(self) -> S: ...

    def get_mut(self) -> S: ...

    def handshake(self) -> object: ...

class Error:
    Normal: "Error"
    Ssl: "Error"
    EmptyChain: "Error"
    NotPkcs8: "Error"

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(err: ErrorStack) -> Exception: ...

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(error: Exception) -> Exception: ...

class HandshakeError:
    Failure: "HandshakeError"
    WouldBlock: "HandshakeError"

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: ErrorStack) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

class HandshakeError:
    Failure: "HandshakeError"
    WouldBlock: "HandshakeError"

    def source(self) -> object: ...

    def fmt(self, fmt: Formatter) -> Result: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: ErrorStack) -> object: ...

    @staticmethod
    def from_(e: object) -> object: ...

    @staticmethod
    def from_(e: Exception) -> object: ...

__all__: list[str] = ["Error", "Identity", "Certificate", "MidHandshakeTlsStream", "TlsConnectorBuilder", "TlsConnector", "TlsAcceptorBuilder", "TlsAcceptor", "TlsStream", "Error", "Identity", "Certificate", "TlsConnector", "TlsAcceptor", "TlsStream", "Identity", "Certificate", "MidHandshakeTlsStream", "TlsConnector", "TlsAcceptor", "TlsStream", "Error", "Identity", "Certificate", "MidHandshakeTlsStream", "TlsConnector", "TlsAcceptor", "TlsStream", "PemBlock", "HandshakeError", "Protocol", "HandshakeError", "MidHandshakeTlsStream", "Error", "HandshakeError", "HandshakeError"]
