"""Python stubs for the josekit Rust crate.

Install with: cookcrab install josekit
"""

from __future__ import annotations

from typing import Self

class EddsaJwsSigner:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def signature_len(self) -> int: ...

    def key_id(self) -> object: ...

    def sign(self, message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class EddsaJwsVerifier:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class EcdsaJwsSigner:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def signature_len(self) -> int: ...

    def key_id(self) -> object: ...

    def sign(self, message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class EcdsaJwsVerifier:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class RsassaPssJwsSigner:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def signature_len(self) -> int: ...

    def key_id(self) -> object: ...

    def sign(self, message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class RsassaPssJwsVerifier:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class HmacJwsSigner:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def signature_len(self) -> int: ...

    def key_id(self) -> object: ...

    def sign(self, message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class HmacJwsVerifier:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class RsassaJwsSigner:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def signature_len(self) -> int: ...

    def key_id(self) -> object: ...

    def sign(self, message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class RsassaJwsVerifier:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class JwsHeader:
    """Represent JWS header claims"""

    @staticmethod
    def new() -> "JwsHeader": ...

    @staticmethod
    def from_bytes(value: object) -> object: ...

    @staticmethod
    def from_map(map: object) -> object: ...

    def set_algorithm(self, value: object) -> None: ...

    def algorithm(self) -> object: ...

    def set_jwk_set_url(self, value: object) -> None: ...

    def jwk_set_url(self) -> object: ...

    def set_jwk(self, value: Jwk) -> None: ...

    def jwk(self) -> Jwk | None: ...

    def set_x509_url(self, value: object) -> None: ...

    def x509_url(self) -> object: ...

    def set_x509_certificate_chain(self, values: object) -> None: ...

    def x509_certificate_chain(self) -> list[list[int]] | None: ...

    def set_x509_certificate_sha1_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha1_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_sha256_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha256_thumbprint(self) -> list[int] | None: ...

    def set_key_id(self, value: object) -> None: ...

    def key_id(self) -> object: ...

    def set_token_type(self, value: object) -> None: ...

    def token_type(self) -> object: ...

    def set_content_type(self, value: object) -> None: ...

    def content_type(self) -> object: ...

    def set_critical(self, values: object) -> None: ...

    def critical(self) -> object: ...

    def set_base64url_encode_payload(self, value: bool) -> None: ...

    def base64url_encode_payload(self) -> bool | None: ...

    def set_url(self, value: object) -> None: ...

    def url(self) -> object: ...

    def set_nonce(self, value: object) -> None: ...

    def nonce(self) -> list[int] | None: ...

    def set_claim(self, key: str, value: Value | None) -> None: ...

    def claims_set(self) -> object: ...

    def into_map(self) -> object: ...

    def len(self) -> int: ...

    def claim(self, key: str) -> object: ...

    def box_clone(self) -> dynJoseHeader: ...

    def as_any(self) -> dynAny: ...

    def as_any_mut(self) -> mutdynAny: ...

    def into_any(self) -> dynAny: ...

    def as_ref(self) -> object: ...

    def into(self) -> object: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class JwsHeaderSet:
    """Represent JWS protected and unprotected header claims"""

    @staticmethod
    def new() -> "JwsHeaderSet": ...

    def set_algorithm(self, value: object, protection: bool) -> None: ...

    def algorithm(self) -> object: ...

    def set_jwk_set_url(self, value: object, protection: bool) -> None: ...

    def jwk_set_url(self) -> object: ...

    def set_jwk(self, value: Jwk, protection: bool) -> None: ...

    def jwk(self) -> Jwk | None: ...

    def set_x509_url(self, value: object, protection: bool) -> None: ...

    def x509_url(self) -> object: ...

    def set_x509_certificate_chain(self, values: object, protection: bool) -> None: ...

    def x509_certificate_chain(self) -> list[list[int]] | None: ...

    def set_x509_certificate_sha1_thumbprint(self, value: object, protection: bool) -> None: ...

    def x509_certificate_sha1_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_sha256_thumbprint(self, value: object, protection: bool) -> None: ...

    def x509_certificate_sha256_thumbprint(self) -> list[int] | None: ...

    def set_key_id(self, value: object, protection: bool) -> None: ...

    def key_id(self) -> object: ...

    def set_token_type(self, value: object, protection: bool) -> None: ...

    def token_type(self) -> object: ...

    def set_content_type(self, value: object, protection: bool) -> None: ...

    def content_type(self) -> object: ...

    def set_critical(self, values: object) -> None: ...

    def critical(self) -> object: ...

    def set_base64url_encode_payload(self, value: bool) -> None: ...

    def base64url_encode_payload(self) -> bool | None: ...

    def set_url(self, value: object, protection: bool) -> None: ...

    def url(self) -> object: ...

    def set_nonce(self, value: object, protection: bool) -> None: ...

    def nonce(self) -> list[int] | None: ...

    def set_claim(self, key: str, value: Value | None, protection: bool) -> None: ...

    def claims_set(self, protection: bool) -> object: ...

    def to_map(self) -> object: ...

    def len(self) -> int: ...

    def claim(self, key: str) -> object: ...

    def box_clone(self) -> dynJoseHeader: ...

    def as_any(self) -> dynAny: ...

    def as_any_mut(self) -> mutdynAny: ...

    def into_any(self) -> dynAny: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class JwsContext:

    @staticmethod
    def new() -> "JwsContext": ...

    def is_acceptable_critical(self, name: str) -> bool: ...

    def add_acceptable_critical(self, name: str) -> None: ...

    def remove_acceptable_critical(self, name: str) -> None: ...

    def serialize_compact(self, payload: object, header: JwsHeader, signer: dynJwsSigner) -> str: ...

    def serialize_compact_with_selector(self, payload: object, header: JwsHeader, selector: F) -> str: ...

    def serialize_general_json(self, payload: object, signers: object) -> str: ...

    def serialize_general_json_with_selecter(self, payload: object, headers: object, selector: F) -> str: ...

    def serialize_flattened_json(self, payload: object, header: JwsHeaderSet, signer: dynJwsSigner) -> str: ...

    def serialize_flattened_json_with_selector(self, payload: object, header: JwsHeaderSet, selector: F) -> str: ...

    def deserialize_compact(self, input: object, verifier: dynJwsVerifier) -> object: ...

    def deserialize_compact_with_selector(self, input: object, selector: F) -> object: ...

    def deserialize_json(self, input: object, verifier: object) -> object: ...

    def deserialize_json_with_selector(self, input: object, selector: F) -> object: ...

class DerBuilder:

    @staticmethod
    def new() -> "DerBuilder": ...

    def begin(self, der_type: DerType) -> None: ...

    def append_integer_from_u8(self, value: int) -> None: ...

    def append_integer_from_u64(self, value: int) -> None: ...

    def append_integer_from_be_slice(self, value: object, sign: bool) -> None: ...

    def append_null(self) -> None: ...

    def append_object_identifier(self, oid: ObjectIdentifier) -> None: ...

    def append_octed_string_from_bytes(self, contents: object) -> None: ...

    def append_bit_string_from_bytes(self, contents: object, trailing_len: int) -> None: ...

    def append(self, der_type: DerType, prefix: int | None, contents: object) -> None: ...

    def end(self) -> None: ...

    def build(self) -> list[int]: ...

class DerReader:

    @staticmethod
    def from_bytes(input: object) -> "DerReader": ...

    @staticmethod
    def from_reader(input: R) -> "DerReader": ...

    def next(self) -> DerType | None: ...

    def skip_contents(self) -> None: ...

    def is_constructed(self) -> bool: ...

    def is_primitive(self) -> bool: ...

    def contents(self) -> object: ...

    def to_null(self) -> None: ...

    def to_boolean(self) -> bool: ...

    def to_u8(self) -> int: ...

    def to_u64(self) -> int: ...

    def to_be_bytes(self, sign: bool, min_len: int) -> list[int]: ...

    def to_vec(self) -> list[int]: ...

    def to_bit_vec(self) -> object: ...

    def to_string(self) -> str: ...

    def to_object_identifier(self) -> ObjectIdentifier: ...

class ObjectIdentifier:

    @staticmethod
    def from_slice(values: object) -> "ObjectIdentifier": ...

    def eq(self, other: str) -> bool: ...

    def fmt(self, f: Formatter) -> Result: ...

class JweContext:

    @staticmethod
    def new() -> "JweContext": ...

    def is_acceptable_critical(self, name: str) -> bool: ...

    def add_acceptable_critical(self, name: str) -> None: ...

    def remove_acceptable_critical(self, name: str) -> None: ...

    def get_compression(self, name: str) -> object: ...

    def add_compression(self, compression: dynJweCompression) -> None: ...

    def remove_compression(self, name: str) -> None: ...

    def get_content_encryption(self, name: str) -> object: ...

    def add_content_encryption(self, content_encryption: dynJweContentEncryption) -> None: ...

    def remove_content_encryption(self, name: str) -> None: ...

    def serialize_compact(self, payload: object, header: JweHeader, encrypter: dynJweEncrypter) -> str: ...

    def serialize_compact_with_selector(self, payload: object, header: JweHeader, selector: F) -> str: ...

    def serialize_general_json(self, payload: object, header: object, recipients: object, aad: object) -> str: ...

    def serialize_general_json_with_selector(self, payload: object, header: object, recipient_headers: object, aad: object, selector: F) -> str: ...

    def serialize_flattened_json(self, payload: object, header: object, recipient_header: object, aad: object, encrypter: dynJweEncrypter) -> str: ...

    def serialize_flattened_json_with_selector(self, payload: object, header: object, recipient_header: object, aad: object, selector: F) -> str: ...

    def deserialize_compact(self, input: object, decrypter: dynJweDecrypter) -> object: ...

    def deserialize_compact_with_selector(self, input: object, selector: F) -> object: ...

    def deserialize_json(self, input: object, decrypter: object) -> object: ...

    def deserialize_json_with_selector(self, input: object, selector: F) -> object: ...

class AeskwJweEncrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, _cencryption: dynJweContentEncryption, _in_header: JweHeader, _out_header: JweHeader) -> object: ...

    def encrypt(self, key: object, _in_header: JweHeader, _out_header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class AeskwJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, _cencryption: dynJweContentEncryption, _header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class DirectJweEncrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, cencryption: dynJweContentEncryption, _merged: JweHeader, _header: JweHeader) -> object: ...

    def encrypt(self, _key: object, _merged: JweHeader, _header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class DirectJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, _cencryption: dynJweContentEncryption, _header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class Pbes2HmacAeskwJweEncrypter:

    def set_salt_len(self, salt_len: int) -> None: ...

    def set_iter_count(self, iter_count: int) -> None: ...

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, _cencryption: dynJweContentEncryption, _in_header: JweHeader, _out_header: JweHeader) -> object: ...

    def encrypt(self, key: object, in_header: JweHeader, out_header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class Pbes2HmacAeskwJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, _cencryption: dynJweContentEncryption, header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class EcdhEsJweEncrypter:

    def set_agreement_partyuinfo(self, value: object) -> None: ...

    def remove_agreement_partyuinfo(self) -> None: ...

    def set_agreement_partyvinfo(self, value: object) -> None: ...

    def remove_agreement_partyvinfo(self) -> None: ...

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, cencryption: dynJweContentEncryption, _merged: JweHeader, header: JweHeader) -> object: ...

    def encrypt(self, key: object, _merged: JweHeader, header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class EcdhEsJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, cencryption: dynJweContentEncryption, header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class AesgcmkwJweEncrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, _cencryption: dynJweContentEncryption, _in_header: JweHeader, _out_header: JweHeader) -> object: ...

    def encrypt(self, key: object, _in_header: JweHeader, out_header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class AesgcmkwJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, _cencryption: dynJweContentEncryption, header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class RsaesJweEncrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def compute_content_encryption_key(self, _cencryption: dynJweContentEncryption, _in_header: JweHeader, _out_header: JweHeader) -> object: ...

    def encrypt(self, key: object, _in_header: JweHeader, _out_header: JweHeader) -> list[int] | None: ...

    def box_clone(self) -> dynJweEncrypter: ...

    def deref(self) -> Target: ...

class RsaesJweDecrypter:

    def set_key_id(self, value: object) -> None: ...

    def remove_key_id(self) -> None: ...

    def algorithm(self) -> dynJweAlgorithm: ...

    def key_id(self) -> object: ...

    def decrypt(self, encrypted_key: object, _cencryption: dynJweContentEncryption, _header: JweHeader) -> object: ...

    def box_clone(self) -> dynJweDecrypter: ...

    def deref(self) -> Target: ...

class JweHeaderSet:
    """Represent JWE protected and unprotected header claims"""

    @staticmethod
    def new() -> "JweHeaderSet": ...

    def set_algorithm(self, value: object, protection: bool) -> None: ...

    def algorithm(self) -> object: ...

    def set_content_encryption(self, value: object, protection: bool) -> None: ...

    def content_encryption(self) -> object: ...

    def set_compression(self, value: object) -> None: ...

    def compression(self) -> object: ...

    def set_jwk_set_url(self, value: object, protection: bool) -> None: ...

    def jwk_set_url(self) -> object: ...

    def set_jwk(self, value: Jwk, protection: bool) -> None: ...

    def jwk(self) -> Jwk | None: ...

    def set_x509_url(self, value: object, protection: bool) -> None: ...

    def x509_url(self) -> object: ...

    def set_x509_certificate_chain(self, values: object, protection: bool) -> None: ...

    def x509_certificate_chain(self) -> list[list[int]] | None: ...

    def set_x509_certificate_sha1_thumbprint(self, value: object, protection: bool) -> None: ...

    def x509_certificate_sha1_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_sha256_thumbprint(self, value: object, protection: bool) -> None: ...

    def x509_certificate_sha256_thumbprint(self) -> list[int] | None: ...

    def set_key_id(self, value: object, protection: bool) -> None: ...

    def key_id(self) -> object: ...

    def set_token_type(self, value: object, protection: bool) -> None: ...

    def token_type(self) -> object: ...

    def set_content_type(self, value: object, protection: bool) -> None: ...

    def content_type(self) -> object: ...

    def set_critical(self, values: object) -> None: ...

    def critical(self) -> object: ...

    def set_url(self, value: object, protection: bool) -> None: ...

    def url(self) -> object: ...

    def set_nonce(self, value: object, protection: bool) -> None: ...

    def nonce(self) -> list[int] | None: ...

    def set_agreement_partyuinfo(self, value: object, protection: bool) -> None: ...

    def agreement_partyuinfo(self) -> list[int] | None: ...

    def set_agreement_partyvinfo(self, value: object, protection: bool) -> None: ...

    def agreement_partyvinfo(self) -> list[int] | None: ...

    def set_issuer(self, value: object, protection: bool) -> None: ...

    def issuer(self) -> object: ...

    def set_subject(self, value: object, protection: bool) -> None: ...

    def subject(self) -> object: ...

    def set_audience(self, values: object, protection: bool) -> None: ...

    def audience(self) -> object: ...

    def set_claim(self, key: str, value: Value | None, protection: bool) -> None: ...

    def claims_set(self, protection: bool) -> object: ...

    def to_map(self) -> object: ...

    def len(self) -> int: ...

    def claim(self, key: str) -> object: ...

    def box_clone(self) -> dynJoseHeader: ...

    def as_any(self) -> dynAny: ...

    def as_any_mut(self) -> mutdynAny: ...

    def into_any(self) -> dynAny: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class JweHeader:
    """Represent JWE header claims"""

    @staticmethod
    def new() -> "JweHeader": ...

    @staticmethod
    def from_bytes(value: object) -> object: ...

    @staticmethod
    def from_map(map: object) -> object: ...

    def set_algorithm(self, value: object) -> None: ...

    def algorithm(self) -> object: ...

    def set_content_encryption(self, value: object) -> None: ...

    def content_encryption(self) -> object: ...

    def set_compression(self, value: object) -> None: ...

    def compression(self) -> object: ...

    def set_jwk_set_url(self, value: object) -> None: ...

    def jwk_set_url(self) -> object: ...

    def set_jwk(self, value: Jwk) -> None: ...

    def jwk(self) -> Jwk | None: ...

    def set_x509_url(self, value: object) -> None: ...

    def x509_url(self) -> object: ...

    def set_x509_certificate_chain(self, values: object) -> None: ...

    def x509_certificate_chain(self) -> list[list[int]] | None: ...

    def set_x509_certificate_sha1_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha1_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_sha256_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha256_thumbprint(self) -> list[int] | None: ...

    def set_key_id(self, value: object) -> None: ...

    def key_id(self) -> object: ...

    def set_token_type(self, value: object) -> None: ...

    def token_type(self) -> object: ...

    def set_content_type(self, value: object) -> None: ...

    def content_type(self) -> object: ...

    def set_critical(self, values: object) -> None: ...

    def critical(self) -> object: ...

    def set_url(self, value: object) -> None: ...

    def url(self) -> object: ...

    def set_nonce(self, value: object) -> None: ...

    def nonce(self) -> list[int] | None: ...

    def set_agreement_partyuinfo(self, value: object) -> None: ...

    def agreement_partyuinfo(self) -> list[int] | None: ...

    def set_agreement_partyvinfo(self, value: object) -> None: ...

    def agreement_partyvinfo(self) -> list[int] | None: ...

    def set_issuer(self, value: object) -> None: ...

    def issuer(self) -> object: ...

    def set_subject(self, value: object) -> None: ...

    def subject(self) -> object: ...

    def set_audience(self, values: object) -> None: ...

    def audience(self) -> object: ...

    def set_claim(self, key: str, value: Value | None) -> None: ...

    def claims_set(self) -> object: ...

    def into_map(self) -> object: ...

    def len(self) -> int: ...

    def claim(self, key: str) -> object: ...

    def box_clone(self) -> dynJoseHeader: ...

    def as_any(self) -> dynAny: ...

    def as_any_mut(self) -> mutdynAny: ...

    def into_any(self) -> dynAny: ...

    def as_ref(self) -> object: ...

    def into(self) -> object: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class EcxKeyPair:

    def set_algorithm(self, value: object) -> None: ...

    def set_key_id(self, key_id: object) -> None: ...

    def curve(self) -> EcxCurve: ...

    @staticmethod
    def generate(curve: EcxCurve) -> "EcxKeyPair": ...

    @staticmethod
    def from_der(input: object) -> object: ...

    @staticmethod
    def from_pem(input: object) -> object: ...

    @staticmethod
    def from_jwk(jwk: Jwk) -> object: ...

    def to_traditional_pem_private_key(self) -> list[int]: ...

    def algorithm(self) -> object: ...

    def key_id(self) -> object: ...

    def to_der_private_key(self) -> list[int]: ...

    def to_der_public_key(self) -> list[int]: ...

    def to_pem_private_key(self) -> list[int]: ...

    def to_pem_public_key(self) -> list[int]: ...

    def to_jwk_private_key(self) -> Jwk: ...

    def to_jwk_public_key(self) -> Jwk: ...

    def to_jwk_key_pair(self) -> Jwk: ...

    def box_clone(self) -> dynKeyPair: ...

    def deref(self) -> Target: ...

class RsaKeyPair:

    def key_len(self) -> int: ...

    def set_algorithm(self, value: object) -> None: ...

    def set_key_id(self, key_id: object) -> None: ...

    def into_rsa_pss_key_pair(self, hash: HashAlgorithm, mgf1_hash: HashAlgorithm, salt_len: int) -> RsaPssKeyPair: ...

    @staticmethod
    def generate(bits: int) -> "RsaKeyPair": ...

    @staticmethod
    def from_der(input: object) -> object: ...

    @staticmethod
    def from_pem(input: object) -> object: ...

    @staticmethod
    def from_jwk(jwk: Jwk) -> object: ...

    def to_raw_private_key(self) -> list[int]: ...

    def to_traditional_pem_private_key(self) -> list[int]: ...

    def to_raw_public_key(self) -> list[int]: ...

    def to_traditional_pem_public_key(self) -> list[int]: ...

    def algorithm(self) -> object: ...

    def key_id(self) -> object: ...

    def to_der_private_key(self) -> list[int]: ...

    def to_der_public_key(self) -> list[int]: ...

    def to_pem_private_key(self) -> list[int]: ...

    def to_pem_public_key(self) -> list[int]: ...

    def to_jwk_private_key(self) -> Jwk: ...

    def to_jwk_public_key(self) -> Jwk: ...

    def to_jwk_key_pair(self) -> Jwk: ...

    def box_clone(self) -> dynKeyPair: ...

    def deref(self) -> Target: ...

class EcKeyPair:

    def curve(self) -> EcCurve: ...

    def set_algorithm(self, value: object) -> None: ...

    def set_key_id(self, key_id: object) -> None: ...

    @staticmethod
    def generate(curve: EcCurve) -> "EcKeyPair": ...

    @staticmethod
    def from_der(input: object, curve: EcCurve | None) -> object: ...

    @staticmethod
    def from_jwk(jwk: Jwk) -> object: ...

    @staticmethod
    def from_pem(input: object, curve: EcCurve | None) -> object: ...

    def to_raw_private_key(self) -> list[int]: ...

    def to_traditional_pem_private_key(self) -> list[int]: ...

    def algorithm(self) -> object: ...

    def key_id(self) -> object: ...

    def to_der_private_key(self) -> list[int]: ...

    def to_der_public_key(self) -> list[int]: ...

    def to_pem_private_key(self) -> list[int]: ...

    def to_pem_public_key(self) -> list[int]: ...

    def to_jwk_private_key(self) -> Jwk: ...

    def to_jwk_public_key(self) -> Jwk: ...

    def to_jwk_key_pair(self) -> Jwk: ...

    def box_clone(self) -> dynKeyPair: ...

    def deref(self) -> Target: ...

class EdKeyPair:

    def set_algorithm(self, value: object) -> None: ...

    def set_key_id(self, key_id: object) -> None: ...

    def curve(self) -> EdCurve: ...

    @staticmethod
    def generate(curve: EdCurve) -> object: ...

    @staticmethod
    def from_der(input: object) -> object: ...

    @staticmethod
    def from_pem(input: object) -> object: ...

    @staticmethod
    def from_jwk(jwk: Jwk) -> object: ...

    def to_traditional_pem_private_key(self) -> list[int]: ...

    def algorithm(self) -> object: ...

    def key_id(self) -> object: ...

    def to_der_private_key(self) -> list[int]: ...

    def to_der_public_key(self) -> list[int]: ...

    def to_pem_private_key(self) -> list[int]: ...

    def to_pem_public_key(self) -> list[int]: ...

    def to_jwk_private_key(self) -> Jwk: ...

    def to_jwk_public_key(self) -> Jwk: ...

    def to_jwk_key_pair(self) -> Jwk: ...

    def box_clone(self) -> dynKeyPair: ...

    def deref(self) -> Target: ...

class RsaPssKeyPair:

    def key_len(self) -> int: ...

    def set_algorithm(self, value: object) -> None: ...

    def set_key_id(self, key_id: object) -> None: ...

    def into_rsa_key_pair(self) -> RsaKeyPair: ...

    @staticmethod
    def generate(bits: int, hash: HashAlgorithm, mgf1_hash: HashAlgorithm, salt_len: int) -> "RsaPssKeyPair": ...

    @staticmethod
    def from_der(input: object, hash: HashAlgorithm | None, mgf1_hash: HashAlgorithm | None, salt_len: int | None) -> object: ...

    @staticmethod
    def from_pem(input: object, hash: HashAlgorithm | None, mgf1_hash: HashAlgorithm | None, salt_len: int | None) -> object: ...

    @staticmethod
    def from_jwk(jwk: Jwk, hash: HashAlgorithm, mgf1_hash: HashAlgorithm, salt_len: int) -> object: ...

    def to_raw_private_key(self) -> list[int]: ...

    def to_raw_public_key(self) -> list[int]: ...

    def to_traditional_pem_private_key(self) -> list[int]: ...

    def algorithm(self) -> object: ...

    def key_id(self) -> object: ...

    def to_der_private_key(self) -> list[int]: ...

    def to_der_public_key(self) -> list[int]: ...

    def to_pem_private_key(self) -> list[int]: ...

    def to_pem_public_key(self) -> list[int]: ...

    def to_jwk_private_key(self) -> Jwk: ...

    def to_jwk_public_key(self) -> Jwk: ...

    def to_jwk_key_pair(self) -> Jwk: ...

    def box_clone(self) -> dynKeyPair: ...

    def deref(self) -> Target: ...

class Jwk:
    """Represents JWK object."""

    @staticmethod
    def new(key_type: str) -> "Jwk": ...

    @staticmethod
    def from_map(map: object) -> object: ...

    @staticmethod
    def from_reader(input: mutdynRead) -> object: ...

    @staticmethod
    def from_bytes(input: object) -> object: ...

    @staticmethod
    def generate_oct_key(key_len: int) -> object: ...

    @staticmethod
    def generate_rsa_key(bits: int) -> object: ...

    @staticmethod
    def generate_ec_key(curve: EcCurve) -> object: ...

    @staticmethod
    def generate_ed_key(curve: EdCurve) -> object: ...

    @staticmethod
    def generate_ecx_key(curve: EcxCurve) -> object: ...

    def to_public_key(self) -> object: ...

    def set_key_type(self, value: object) -> None: ...

    def key_type(self) -> str: ...

    def set_key_use(self, value: object) -> None: ...

    def key_use(self) -> object: ...

    def set_key_operations(self, values: object) -> None: ...

    def key_operations(self) -> object: ...

    def is_for_key_operation(self, key_operation: str) -> bool: ...

    def set_algorithm(self, value: object) -> None: ...

    def algorithm(self) -> object: ...

    def set_key_id(self, value: object) -> None: ...

    def key_id(self) -> object: ...

    def set_x509_url(self, value: object) -> None: ...

    def x509_url(self) -> object: ...

    def set_x509_certificate_sha1_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha1_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_sha256_thumbprint(self, value: object) -> None: ...

    def x509_certificate_sha256_thumbprint(self) -> list[int] | None: ...

    def set_x509_certificate_chain(self, values: object) -> None: ...

    def x509_certificate_chain(self) -> list[list[int]] | None: ...

    def set_curve(self, value: object) -> None: ...

    def curve(self) -> object: ...

    def set_key_value(self, value: object) -> None: ...

    def key_value(self) -> list[int] | None: ...

    def set_parameter(self, key: str, value: Value | None) -> None: ...

    def parameter(self, key: str) -> object: ...

    def as_ref(self) -> object: ...

    def into(self) -> object: ...

    def fmt(self, fmt: Formatter) -> None: ...

class KeyInfo:

    def format(self) -> KeyFormat: ...

    def alg(self) -> KeyAlg | None: ...

    def is_public_key(self) -> bool: ...

    @staticmethod
    def detect(input: object) -> KeyInfo | None: ...

class JwkSet:
    """Represents JWK set."""

    @staticmethod
    def new() -> "JwkSet": ...

    @staticmethod
    def from_map(map: object) -> object: ...

    @staticmethod
    def from_reader(input: mutdynRead) -> object: ...

    @staticmethod
    def from_bytes(input: object) -> object: ...

    def get(self, key_id: str) -> object: ...

    def keys(self) -> object: ...

    def push_key(self, jwk: Jwk) -> None: ...

    def remove_key(self, jwk: Jwk) -> None: ...

    def as_ref(self) -> object: ...

    def into(self) -> object: ...

    def fmt(self, fmt: Formatter) -> None: ...

class JwtPayload:

    @staticmethod
    def new() -> "JwtPayload": ...

    @staticmethod
    def from_map(map: object) -> object: ...

    def set_issuer(self, value: object) -> None: ...

    def issuer(self) -> object: ...

    def set_subject(self, value: object) -> None: ...

    def subject(self) -> object: ...

    def set_audience(self, values: object) -> None: ...

    def audience(self) -> object: ...

    def set_expires_at(self, value: SystemTime) -> None: ...

    def expires_at(self) -> SystemTime | None: ...

    def set_not_before(self, value: SystemTime) -> None: ...

    def not_before(self) -> SystemTime | None: ...

    def set_issued_at(self, value: SystemTime) -> None: ...

    def issued_at(self) -> SystemTime | None: ...

    def set_jwt_id(self, value: object) -> None: ...

    def jwt_id(self) -> object: ...

    def set_claim(self, key: str, value: Value | None) -> None: ...

    def claim(self, key: str) -> object: ...

    def claims_set(self) -> object: ...

    def as_ref(self) -> object: ...

    def into(self) -> object: ...

    def fmt(self, fmt: Formatter) -> None: ...

class UnsecuredJwsSigner:

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def signature_len(self) -> int: ...

    def sign(self, _message: object) -> list[int]: ...

    def box_clone(self) -> dynJwsSigner: ...

    def deref(self) -> Target: ...

class UnsecuredJwsVerifier:

    def algorithm(self) -> dynJwsAlgorithm: ...

    def key_id(self) -> object: ...

    def verify(self, _message: object, signature: object) -> None: ...

    def box_clone(self) -> dynJwsVerifier: ...

    def deref(self) -> Target: ...

class JwtPayloadValidator:
    """Represents JWT payload validator."""

    @staticmethod
    def new() -> "JwtPayloadValidator": ...

    def set_base_time(self, base_time: SystemTime) -> None: ...

    def base_time(self) -> object: ...

    def set_min_issued_time(self, min_issued_time: SystemTime) -> None: ...

    def min_issued_time(self) -> object: ...

    def set_max_issued_time(self, max_issued_time: SystemTime) -> None: ...

    def max_issued_time(self) -> object: ...

    def set_issuer(self, value: object) -> None: ...

    def issuer(self) -> object: ...

    def set_subject(self, value: object) -> None: ...

    def subject(self) -> object: ...

    def set_audience(self, value: object) -> None: ...

    def audience(self) -> object: ...

    def set_jwt_id(self, value: object) -> None: ...

    def jwt_id(self) -> object: ...

    def set_claim(self, key: str, value: Value) -> None: ...

    def claim(self, key: str) -> object: ...

    def validate(self, payload: JwtPayload) -> None: ...

class JwtContext:

    @staticmethod
    def new() -> "JwtContext": ...

    def is_acceptable_critical(self, name: str) -> bool: ...

    def add_acceptable_critical(self, name: str) -> None: ...

    def remove_acceptable_critical(self, name: str) -> None: ...

    def encode_unsecured(self, payload: JwtPayload, header: JwsHeader) -> str: ...

    def encode_with_signer(self, payload: JwtPayload, header: JwsHeader, signer: dynJwsSigner) -> str: ...

    def encode_with_encrypter(self, payload: JwtPayload, header: JweHeader, encrypter: dynJweEncrypter) -> str: ...

    def decode_header(self, input: object) -> dynJoseHeader: ...

    def decode_unsecured(self, input: object) -> object: ...

    def decode_with_verifier(self, input: object, verifier: dynJwsVerifier) -> object: ...

    def decode_with_verifier_selector(self, input: object, selector: F) -> object: ...

    def decode_with_verifier_in_jwk_set(self, input: object, jwk_set: JwkSet, selector: F) -> object: ...

    def decode_with_decrypter(self, input: object, decrypter: dynJweDecrypter) -> object: ...

    def decode_with_decrypter_selector(self, input: object, selector: F) -> object: ...

    def decode_with_decrypter_in_jwk_set(self, input: object, jwk_set: JwkSet, selector: F) -> object: ...

class EddsaJwsAlgorithm:
    Eddsa: "EddsaJwsAlgorithm"

    def generate_key_pair(self, curve: EdCurve) -> EdKeyPair: ...

    def key_pair_from_der(self, input: object) -> EdKeyPair: ...

    def key_pair_from_pem(self, input: object) -> EdKeyPair: ...

    def signer_from_der(self, input: object) -> EddsaJwsSigner: ...

    def signer_from_pem(self, input: object) -> EddsaJwsSigner: ...

    def signer_from_jwk(self, jwk: Jwk) -> EddsaJwsSigner: ...

    def verifier_from_der(self, input: object) -> EddsaJwsVerifier: ...

    def verifier_from_pem(self, input: object) -> EddsaJwsVerifier: ...

    def verifier_from_jwk(self, jwk: Jwk) -> EddsaJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class EcdsaJwsAlgorithm:
    Es256: "EcdsaJwsAlgorithm"
    Es384: "EcdsaJwsAlgorithm"
    Es512: "EcdsaJwsAlgorithm"
    Es256k: "EcdsaJwsAlgorithm"

    def generate_key_pair(self) -> EcKeyPair: ...

    def key_pair_from_der(self, input: object) -> EcKeyPair: ...

    def key_pair_from_pem(self, input: object) -> EcKeyPair: ...

    def signer_from_der(self, input: object) -> EcdsaJwsSigner: ...

    def signer_from_pem(self, input: object) -> EcdsaJwsSigner: ...

    def signer_from_jwk(self, jwk: Jwk) -> EcdsaJwsSigner: ...

    def verifier_from_der(self, input: object) -> EcdsaJwsVerifier: ...

    def verifier_from_pem(self, input: object) -> EcdsaJwsVerifier: ...

    def verifier_from_jwk(self, jwk: Jwk) -> EcdsaJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class RsassaPssJwsAlgorithm:
    Ps256: "RsassaPssJwsAlgorithm"
    Ps384: "RsassaPssJwsAlgorithm"
    Ps512: "RsassaPssJwsAlgorithm"

    def generate_key_pair(self, bits: int) -> RsaPssKeyPair: ...

    def key_pair_from_der(self, input: object) -> RsaPssKeyPair: ...

    def key_pair_from_pem(self, input: object) -> RsaPssKeyPair: ...

    def signer_from_der(self, input: object) -> RsassaPssJwsSigner: ...

    def signer_from_pem(self, input: object) -> RsassaPssJwsSigner: ...

    def signer_from_jwk(self, jwk: Jwk) -> RsassaPssJwsSigner: ...

    def verifier_from_der(self, input: object) -> RsassaPssJwsVerifier: ...

    def verifier_from_pem(self, input: object) -> RsassaPssJwsVerifier: ...

    def verifier_from_jwk(self, jwk: Jwk) -> RsassaPssJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class HmacJwsAlgorithm:
    Hs256: "HmacJwsAlgorithm"
    Hs384: "HmacJwsAlgorithm"
    Hs512: "HmacJwsAlgorithm"

    def to_jwk(self, secret: object) -> Jwk: ...

    def signer_from_bytes(self, input: object) -> HmacJwsSigner: ...

    def signer_from_jwk(self, jwk: Jwk) -> HmacJwsSigner: ...

    def verifier_from_bytes(self, input: object) -> HmacJwsVerifier: ...

    def verifier_from_jwk(self, jwk: Jwk) -> HmacJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class RsassaJwsAlgorithm:
    Rs256: "RsassaJwsAlgorithm"
    Rs384: "RsassaJwsAlgorithm"
    Rs512: "RsassaJwsAlgorithm"

    def generate_key_pair(self, bits: int) -> RsaKeyPair: ...

    def key_pair_from_der(self, input: object) -> RsaKeyPair: ...

    def key_pair_from_pem(self, input: object) -> RsaKeyPair: ...

    def signer_from_der(self, input: object) -> RsassaJwsSigner: ...

    def signer_from_pem(self, input: object) -> RsassaJwsSigner: ...

    def signer_from_jwk(self, jwk: Jwk) -> RsassaJwsSigner: ...

    def verifier_from_der(self, input: object) -> RsassaJwsVerifier: ...

    def verifier_from_pem(self, input: object) -> RsassaJwsVerifier: ...

    def verifier_from_jwk(self, jwk: Jwk) -> RsassaJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class HashAlgorithm:
    Sha1: "HashAlgorithm"
    Sha256: "HashAlgorithm"
    Sha384: "HashAlgorithm"
    Sha512: "HashAlgorithm"

    def name(self) -> str: ...

    def output_len(self) -> int: ...

    def fmt(self, fmt: Formatter) -> None: ...

class DerClass:
    Universal: "DerClass"
    Application: "DerClass"
    ContextSpecific: "DerClass"
    Private: "DerClass"

    def class_no(self) -> int: ...

    def fmt(self, f: Formatter) -> Result: ...

class DerType:
    EndOfContents: "DerType"
    Boolean: "DerType"
    Integer: "DerType"
    BitString: "DerType"
    OctetString: "DerType"
    Null: "DerType"
    ObjectIdentifier: "DerType"
    ObjectDescriptor: "DerType"
    External: "DerType"
    Real: "DerType"
    Enumerated: "DerType"
    EmbeddedPdv: "DerType"
    Utf8String: "DerType"
    RelativeOid: "DerType"
    Time: "DerType"
    Sequence: "DerType"
    Set: "DerType"
    NumericString: "DerType"
    PrintableString: "DerType"
    TeletexString: "DerType"
    VideotexString: "DerType"
    Ia5String: "DerType"
    UtcTime: "DerType"
    GeneralizedTime: "DerType"
    GraphicString: "DerType"
    VisibleString: "DerType"
    GeneralString: "DerType"
    UniversalString: "DerType"
    CharacterString: "DerType"
    BmpString: "DerType"
    Date: "DerType"
    TimeOfDay: "DerType"
    DateTime: "DerType"
    Duration: "DerType"
    Other: "DerType"

    def can_primitive(self) -> bool: ...

    def can_constructed(self) -> bool: ...

    def der_class(self) -> DerClass: ...

    def tag_no(self) -> int: ...

    def fmt(self, f: Formatter) -> Result: ...

class DerError:
    UnexpectedEndOfInput: "DerError"
    InvalidTag: "DerError"
    InvalidLength: "DerError"
    InvalidContents: "DerError"
    Overflow: "DerError"
    ReadFailure: "DerError"

class AeskwJweAlgorithm:
    A128kw: "AeskwJweAlgorithm"
    A192kw: "AeskwJweAlgorithm"
    A256kw: "AeskwJweAlgorithm"

    def encrypter_from_bytes(self, input: object) -> AeskwJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> AeskwJweEncrypter: ...

    def decrypter_from_bytes(self, input: object) -> AeskwJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> AeskwJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class DirectJweAlgorithm:
    Dir: "DirectJweAlgorithm"

    def encrypter_from_bytes(self, input: object) -> DirectJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> DirectJweEncrypter: ...

    def decrypter_from_bytes(self, input: object) -> DirectJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> DirectJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class Pbes2HmacAeskwJweAlgorithm:
    Pbes2Hs256A128kw: "Pbes2HmacAeskwJweAlgorithm"
    Pbes2Hs384A192kw: "Pbes2HmacAeskwJweAlgorithm"
    Pbes2Hs512A256kw: "Pbes2HmacAeskwJweAlgorithm"

    def encrypter_from_bytes(self, input: object) -> Pbes2HmacAeskwJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> Pbes2HmacAeskwJweEncrypter: ...

    def decrypter_from_bytes(self, input: object) -> Pbes2HmacAeskwJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> Pbes2HmacAeskwJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class EcdhEsJweAlgorithm:
    EcdhEs: "EcdhEsJweAlgorithm"
    EcdhEsA128kw: "EcdhEsJweAlgorithm"
    EcdhEsA192kw: "EcdhEsJweAlgorithm"
    EcdhEsA256kw: "EcdhEsJweAlgorithm"

    def generate_ec_key_pair(self, curve: EcCurve) -> EcKeyPair: ...

    def generate_ecx_key_pair(self, curve: EcxCurve) -> EcxKeyPair: ...

    def key_pair_from_ec_der(self, input: object) -> EcKeyPair: ...

    def key_pair_from_ecx_der(self, input: object) -> EcxKeyPair: ...

    def key_pair_from_ec_pem(self, input: object) -> EcKeyPair: ...

    def key_pair_from_ecx_pem(self, input: object) -> EcxKeyPair: ...

    def encrypter_from_der(self, input: object) -> EcdhEsJweEncrypter: ...

    def encrypter_from_pem(self, input: object) -> EcdhEsJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> EcdhEsJweEncrypter: ...

    def decrypter_from_der(self, input: object) -> EcdhEsJweDecrypter: ...

    def decrypter_from_pem(self, input: object) -> EcdhEsJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> EcdhEsJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class AesgcmkwJweAlgorithm:
    A128gcmkw: "AesgcmkwJweAlgorithm"
    A192gcmkw: "AesgcmkwJweAlgorithm"
    A256gcmkw: "AesgcmkwJweAlgorithm"

    def encrypter_from_bytes(self, input: object) -> AesgcmkwJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> AesgcmkwJweEncrypter: ...

    def decrypter_from_bytes(self, input: object) -> AesgcmkwJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> AesgcmkwJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class RsaesJweAlgorithm:
    Rsa1_5: "RsaesJweAlgorithm"
    RsaOaep: "RsaesJweAlgorithm"
    RsaOaep256: "RsaesJweAlgorithm"
    RsaOaep384: "RsaesJweAlgorithm"
    RsaOaep512: "RsaesJweAlgorithm"

    def generate_key_pair(self, bits: int) -> RsaKeyPair: ...

    def key_pair_from_der(self, input: object) -> RsaKeyPair: ...

    def key_pair_from_pem(self, input: object) -> RsaKeyPair: ...

    def encrypter_from_der(self, input: object) -> RsaesJweEncrypter: ...

    def encrypter_from_pem(self, input: object) -> RsaesJweEncrypter: ...

    def encrypter_from_jwk(self, jwk: Jwk) -> RsaesJweEncrypter: ...

    def decrypter_from_der(self, input: object) -> RsaesJweDecrypter: ...

    def decrypter_from_pem(self, input: object) -> RsaesJweDecrypter: ...

    def decrypter_from_jwk(self, jwk: Jwk) -> RsaesJweDecrypter: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJweAlgorithm: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class DeflateJweCompression:
    Def: "DeflateJweCompression"

    def name(self) -> str: ...

    def compress(self, message: object) -> list[int]: ...

    def decompress(self, data: object) -> list[int]: ...

    def box_clone(self) -> dynJweCompression: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class AesgcmJweEncryption:
    A128gcm: "AesgcmJweEncryption"
    A192gcm: "AesgcmJweEncryption"
    A256gcm: "AesgcmJweEncryption"

    def name(self) -> str: ...

    def key_len(self) -> int: ...

    def iv_len(self) -> int: ...

    def encrypt(self, key: object, iv: object, message: object, aad: object) -> object: ...

    def decrypt(self, key: object, iv: object, encrypted_message: object, aad: object, tag: object) -> list[int]: ...

    def box_clone(self) -> dynJweContentEncryption: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class AescbcHmacJweEncryption:
    A128cbcHs256: "AescbcHmacJweEncryption"
    A192cbcHs384: "AescbcHmacJweEncryption"
    A256cbcHs512: "AescbcHmacJweEncryption"

    def name(self) -> str: ...

    def key_len(self) -> int: ...

    def iv_len(self) -> int: ...

    def encrypt(self, key: object, iv: object, message: object, aad: object) -> object: ...

    def decrypt(self, key: object, iv: object, encrypted_message: object, aad: object, tag: object) -> list[int]: ...

    def box_clone(self) -> dynJweContentEncryption: ...

    def fmt(self, fmt: Formatter) -> None: ...

    def deref(self) -> Target: ...

class EcxCurve:
    X25519: "EcxCurve"
    X448: "EcxCurve"

    def name(self) -> str: ...

    def oid(self) -> ObjectIdentifier: ...

    def fmt(self, fmt: Formatter) -> None: ...

class EcCurve:
    P256: "EcCurve"
    P384: "EcCurve"
    P521: "EcCurve"
    Secp256k1: "EcCurve"

    def name(self) -> str: ...

    def oid(self) -> ObjectIdentifier: ...

    def fmt(self, fmt: Formatter) -> None: ...

class EdCurve:
    Ed25519: "EdCurve"
    Ed448: "EdCurve"

    def name(self) -> str: ...

    def oid(self) -> ObjectIdentifier: ...

    def fmt(self, fmt: Formatter) -> None: ...

class KeyAlg:
    Rsa: "KeyAlg"
    RsaPss: "KeyAlg"
    Ec: "KeyAlg"
    Ed: "KeyAlg"
    Ecx: "KeyAlg"

class KeyFormat:
    Der: "KeyFormat"
    Pem: "KeyFormat"
    Jwk: "KeyFormat"

class UnsecuredJwsAlgorithm:
    None_: "UnsecuredJwsAlgorithm"

    def signer(self) -> UnsecuredJwsSigner: ...

    def verifier(self) -> UnsecuredJwsVerifier: ...

    def name(self) -> str: ...

    def box_clone(self) -> dynJwsAlgorithm: ...

    def deref(self) -> Target: ...

class JoseError:
    UnsupportedSignatureAlgorithm: "JoseError"
    InvalidJwtFormat: "JoseError"
    InvalidJwkFormat: "JoseError"
    InvalidJwsFormat: "JoseError"
    InvalidJweFormat: "JoseError"
    InvalidKeyFormat: "JoseError"
    InvalidJson: "JoseError"
    InvalidClaim: "JoseError"
    InvalidSignature: "JoseError"

def random_bytes(len: int) -> list[int]: ...

"""Return a representation of the data that is formatted by compact serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS heaser claims.
* `encrypter` - The JWS encrypter."""
def serialize_compact(payload: object, header: JweHeader, encrypter: dynJweEncrypter) -> str: ...

"""Return a representation of the data that is formatted by compact serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS heaser claims.
* `selector` - a function for selecting the signing algorithm."""
def serialize_compact_with_selector(payload: object, header: JweHeader, selector: F) -> str: ...

"""Return a representation of the data that is formatted by flattened json serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWE shared protected and unprotected header claims.
* `recipients` - The JWE header claims and the JWE encrypter pair for recipients.
* `aad` - The JWE additional authenticated data."""
def serialize_general_json(payload: object, header: object, recipients: object, aad: object) -> str: ...

"""Return a representation of the data that is formatted by flattened json serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS shared protected and unprotected header claims.
* `recipient_headers` - The JWE unprotected header claims for recipients.
* `aad` - The JWE additional authenticated data.
* `selector` - a function for selecting the encrypting algorithm."""
def serialize_general_json_with_selector(payload: object, header: object, recipient_headers: object, aad: object, selector: F) -> str: ...

"""Return a representation of the data that is formatted by flattened json serialization.

# Arguments

* `header` - The JWE shared protected and unprotected header claims.
* `recipient_header` - The JWE unprotected header claims.
* `aad` - The JWE additional authenticated data.
* `payload` - The payload data.
* `encrypter` - The JWS encrypter."""
def serialize_flattened_json(payload: object, header: object, recipient_header: object, aad: object, encrypter: dynJweEncrypter) -> str: ...

"""Return a representation of the data that is formatted by flatted json serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS shared protected and unprotected header claims.
* `recipient_header` - The JWS unprotected header claims.
* `aad` - The JWE additional authenticated data.
* `selector` - a function for selecting the encrypting algorithm."""
def serialize_flattened_json_with_selector(payload: object, header: object, recipient_header: object, aad: object, selector: F) -> str: ...

"""Deserialize the input that is formatted by compact serialization.

# Arguments

* `input` - The input data.
* `decrypter` - The JWS decrypter."""
def deserialize_compact(input: str, decrypter: dynJweDecrypter) -> object: ...

"""Deserialize the input that is formatted by compact serialization.

# Arguments

* `input` - The input data.
* `selector` - a function for selecting the decrypting algorithm."""
def deserialize_compact_with_selector(input: str, selector: F) -> object: ...

"""Deserialize the input that is formatted by flattened json serialization.

# Arguments

* `input` - The input data.
* `header` - The decoded JWS header claims.
* `decrypter` - The JWE decrypter."""
def deserialize_json(input: str, decrypter: object) -> object: ...

"""Deserialize the input that is formatted by flattened json serialization.

# Arguments

* `input` - The input data.
* `selector` - a function for selecting the decrypting algorithm."""
def deserialize_json_with_selector(input: str, selector: F) -> object: ...

"""Return a representation of the data that is formatted by compact serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS heaser claims.
* `signer` - The JWS signer."""
def serialize_compact(payload: object, header: JwsHeader, signer: dynJwsSigner) -> str: ...

"""Return a representation of the data that is formatted by compact serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS heaser claims.
* `selector` - a function for selecting the signing algorithm."""
def serialize_compact_with_selector(payload: object, header: JwsHeader, selector: F) -> str: ...

"""Return a representation of the data that is formatted by general json serialization.

# Arguments

* `protected` - The JWS protected header claims.
* `header` - The JWS unprotected header claims.
* `payload` - The payload data.
* `signers` - The JWS signer."""
def serialize_general_json(payload: object, signers: object) -> str: ...

"""Return a representation of the data that is formatted by general json serialization.

# Arguments

* `payload` - The payload data.
* `headers` - The protected and unprotected header claims.
* `selector` - a function for selecting the signing algorithm."""
def serialize_general_json_with_selecter(payload: object, headers: object, selector: F) -> str: ...

"""Return a representation of the data that is formatted by flattened json serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS protected and unprotected header claims.
* `signer` - The JWS signer."""
def serialize_flattened_json(payload: object, header: JwsHeaderSet, signer: dynJwsSigner) -> str: ...

"""Return a representation of the data that is formatted by flatted json serialization.

# Arguments

* `payload` - The payload data.
* `header` - The JWS protected and unprotected header claims.
* `selector` - a function for selecting the signing algorithm."""
def serialize_flattened_json_with_selector(payload: object, header: JwsHeaderSet, selector: F) -> str: ...

"""Deserialize the input that is formatted by compact serialization.

# Arguments

* `input` - The input data.
* `header` - The decoded JWS header claims.
* `verifier` - The JWS verifier."""
def deserialize_compact(input: object, verifier: dynJwsVerifier) -> object: ...

"""Deserialize the input that is formatted by compact serialization.

# Arguments

* `input` - The input data.
* `header` - The decoded JWS header claims.
* `selector` - a function for selecting the verifying algorithm."""
def deserialize_compact_with_selector(input: object, selector: F) -> object: ...

"""Deserialize the input that is formatted by json serialization.

# Arguments

* `input` - The input data.
* `header` - The decoded JWS header claims.
* `verifier` - The JWS verifier."""
def deserialize_json(input: object, verifier: object) -> object: ...

"""Deserialize the input that is formatted by json serialization.

# Arguments

* `input` - The input data.
* `header` - The decoded JWS header claims.
* `selector` - a function for selecting the verifying algorithm."""
def deserialize_json_with_selector(input: object, selector: F) -> object: ...

"""Return the string repsentation of the JWT with a "none" algorithm.

# Arguments

* `payload` - The payload data.
* `header` - The JWT heaser claims."""
def encode_unsecured(payload: JwtPayload, header: JwsHeader) -> str: ...

"""Return the string repsentation of the JWT with the siginig algorithm.

# Arguments

* `payload` - The payload data.
* `header` - The JWS heaser claims.
* `signer` - a signer object."""
def encode_with_signer(payload: JwtPayload, header: JwsHeader, signer: dynJwsSigner) -> str: ...

"""Return the string repsentation of the JWT with the encrypting algorithm.

# Arguments

* `payload` - The payload data.
* `header` - The JWE heaser claims.
* `encrypter` - a encrypter object."""
def encode_with_encrypter(payload: JwtPayload, header: JweHeader, encrypter: dynJweEncrypter) -> str: ...

"""Return the Jose header decoded from JWT.

# Arguments

* `input` - a JWT string representation."""
def decode_header(input: object) -> dynJoseHeader: ...

"""Return the JWT object decoded with the "none" algorithm.

# Arguments

* `input` - a JWT string representation."""
def decode_unsecured(input: object) -> object: ...

"""Return the JWT object decoded by the selected verifier.

# Arguments

* `verifier` - a verifier of the signing algorithm.
* `input` - a JWT string representation."""
def decode_with_verifier(input: object, verifier: dynJwsVerifier) -> object: ...

"""Return the JWT object decoded with a selected verifying algorithm.

# Arguments

* `input` - a JWT string representation.
* `selector` - a function for selecting the verifying algorithm."""
def decode_with_verifier_selector(input: object, selector: F) -> object: ...

"""Return the JWT object decoded by using a JWK set.

# Arguments

* `input` - a JWT string representation.
* `jwk_set` - a JWK set.
* `selector` - a function for selecting the verifying algorithm."""
def decode_with_verifier_in_jwk_set(input: object, jwk_set: JwkSet, selector: F) -> object: ...

"""Return the JWT object decoded by the selected decrypter.

# Arguments

* `input` - a JWT string representation.
* `decrypter` - a decrypter of the decrypting algorithm."""
def decode_with_decrypter(input: object, decrypter: dynJweDecrypter) -> object: ...

"""Return the JWT object decoded with a selected decrypting algorithm.

# Arguments

* `input` - a JWT string representation.
* `decrypter_selector` - a function for selecting the decrypting algorithm."""
def decode_with_decrypter_selector(input: object, selector: F) -> object: ...

"""Return the JWT object decoded by using a JWK set.

# Arguments

* `input` - a JWT string representation.
* `jwk_set` - a JWK set.
* `selector` - a function for selecting the decrypting algorithm."""
def decode_with_decrypter_in_jwk_set(input: object, jwk_set: JwkSet, selector: F) -> object: ...

# ====================================================
# Algorithm/Variant Constants - convenient top-level exports
# ====================================================

SHA_1: HashAlgorithm
SHA_256: HashAlgorithm
SHA_384: HashAlgorithm
SHA_512: HashAlgorithm
ECDH_ES: EcdhEsJweAlgorithm
ECDH_ES_A128KW: EcdhEsJweAlgorithm
ECDH_ES_A192KW: EcdhEsJweAlgorithm
ECDH_ES_A256KW: EcdhEsJweAlgorithm
A128KW: AeskwJweAlgorithm
A192KW: AeskwJweAlgorithm
A256KW: AeskwJweAlgorithm
A128GCMKW: AesgcmkwJweAlgorithm
A192GCMKW: AesgcmkwJweAlgorithm
A256GCMKW: AesgcmkwJweAlgorithm
PBES2_HS256_A128KW: Pbes2HmacAeskwJweAlgorithm
PBES2_HS384_A192KW: Pbes2HmacAeskwJweAlgorithm
PBES2_HS512_A256KW: Pbes2HmacAeskwJweAlgorithm
RSA1_5: RsaesJweAlgorithm
RSA_OAEP: RsaesJweAlgorithm
RSA_OAEP_256: RsaesJweAlgorithm
RSA_OAEP_384: RsaesJweAlgorithm
RSA_OAEP_512: RsaesJweAlgorithm
A128CBC_HS256: AescbcHmacJweEncryption
A192CBC_HS384: AescbcHmacJweEncryption
A256CBC_HS512: AescbcHmacJweEncryption
A128GCM: AesgcmJweEncryption
A192GCM: AesgcmJweEncryption
A256GCM: AesgcmJweEncryption
HS256: HmacJwsAlgorithm
HS384: HmacJwsAlgorithm
HS512: HmacJwsAlgorithm
RS256: RsassaJwsAlgorithm
RS384: RsassaJwsAlgorithm
RS512: RsassaJwsAlgorithm
PS256: RsassaPssJwsAlgorithm
PS384: RsassaPssJwsAlgorithm
PS512: RsassaPssJwsAlgorithm
ES256: EcdsaJwsAlgorithm
ES256K: EcdsaJwsAlgorithm
ES384: EcdsaJwsAlgorithm
ES512: EcdsaJwsAlgorithm
EdDSA: EddsaJwsAlgorithm

# ====================================================
# Module-level Constants
# ====================================================

Dir: DirectJweAlgorithm = ...

__all__: list[str] = ["random_bytes", "serialize_compact", "serialize_compact_with_selector", "serialize_general_json", "serialize_general_json_with_selector", "serialize_flattened_json", "serialize_flattened_json_with_selector", "deserialize_compact", "deserialize_compact_with_selector", "deserialize_json", "deserialize_json_with_selector", "serialize_compact", "serialize_compact_with_selector", "serialize_general_json", "serialize_general_json_with_selecter", "serialize_flattened_json", "serialize_flattened_json_with_selector", "deserialize_compact", "deserialize_compact_with_selector", "deserialize_json", "deserialize_json_with_selector", "encode_unsecured", "encode_with_signer", "encode_with_encrypter", "decode_header", "decode_unsecured", "decode_with_verifier", "decode_with_verifier_selector", "decode_with_verifier_in_jwk_set", "decode_with_decrypter", "decode_with_decrypter_selector", "decode_with_decrypter_in_jwk_set", "EddsaJwsSigner", "EddsaJwsVerifier", "EcdsaJwsSigner", "EcdsaJwsVerifier", "RsassaPssJwsSigner", "RsassaPssJwsVerifier", "HmacJwsSigner", "HmacJwsVerifier", "RsassaJwsSigner", "RsassaJwsVerifier", "JwsHeader", "JwsHeaderSet", "JwsContext", "DerBuilder", "DerReader", "ObjectIdentifier", "JweContext", "AeskwJweEncrypter", "AeskwJweDecrypter", "DirectJweEncrypter", "DirectJweDecrypter", "Pbes2HmacAeskwJweEncrypter", "Pbes2HmacAeskwJweDecrypter", "EcdhEsJweEncrypter", "EcdhEsJweDecrypter", "AesgcmkwJweEncrypter", "AesgcmkwJweDecrypter", "RsaesJweEncrypter", "RsaesJweDecrypter", "JweHeaderSet", "JweHeader", "EcxKeyPair", "RsaKeyPair", "EcKeyPair", "EdKeyPair", "RsaPssKeyPair", "Jwk", "KeyInfo", "JwkSet", "JwtPayload", "UnsecuredJwsSigner", "UnsecuredJwsVerifier", "JwtPayloadValidator", "JwtContext", "EddsaJwsAlgorithm", "EcdsaJwsAlgorithm", "RsassaPssJwsAlgorithm", "HmacJwsAlgorithm", "RsassaJwsAlgorithm", "HashAlgorithm", "DerClass", "DerType", "DerError", "AeskwJweAlgorithm", "DirectJweAlgorithm", "Pbes2HmacAeskwJweAlgorithm", "EcdhEsJweAlgorithm", "AesgcmkwJweAlgorithm", "RsaesJweAlgorithm", "DeflateJweCompression", "AesgcmJweEncryption", "AescbcHmacJweEncryption", "EcxCurve", "EcCurve", "EdCurve", "KeyAlg", "KeyFormat", "UnsecuredJwsAlgorithm", "JoseError", "SHA_1", "SHA_256", "SHA_384", "SHA_512", "ECDH_ES", "ECDH_ES_A128KW", "ECDH_ES_A192KW", "ECDH_ES_A256KW", "A128KW", "A192KW", "A256KW", "A128GCMKW", "A192GCMKW", "A256GCMKW", "PBES2_HS256_A128KW", "PBES2_HS384_A192KW", "PBES2_HS512_A256KW", "RSA1_5", "RSA_OAEP", "RSA_OAEP_256", "RSA_OAEP_384", "RSA_OAEP_512", "A128CBC_HS256", "A192CBC_HS384", "A256CBC_HS512", "A128GCM", "A192GCM", "A256GCM", "HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES256K", "ES384", "ES512", "EdDSA", "Dir"]
